// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("xmodel/character_airborne_officer_winter");
	self attach("xmodel/head_Foley");
	self.hatModel = "xmodel/gear_US_helmet_captain";
	self attach(self.hatModel);
	self.voice = "foley";
}

precache()
{
	precacheModel("xmodel/character_airborne_officer_winter");
	precacheModel("xmodel/head_Foley");
	precacheModel("xmodel/gear_US_helmet_captain");
}
