// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("xmodel/character_german_tankcrew");
	character\_utility::attachFromArray(xmodelalias\head_axis::main());
	self.hatModel = "xmodel/german_tank_OfficerHat";
	self attach(self.hatModel);
	self.voice = "german";
}

precache()
{
	precacheModel("xmodel/character_german_tankcrew");
	character\_utility::precacheModelArray(xmodelalias\head_axis::main());
	precacheModel("xmodel/german_tank_OfficerHat");
}
