// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	character\_utility::setModelFromArray(xmodelalias\body_British_Commando::main());
	self attach("xmodel/head_ingram");
	self.hatModel = "xmodel/equipment_british_beret_green";
	self attach(self.hatModel);
	self.voice = "ingram";
}

precache()
{
	character\_utility::precacheModelArray(xmodelalias\body_British_Commando::main());
	precacheModel("xmodel/head_ingram");
	precacheModel("xmodel/equipment_british_beret_green");
}
