// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("xmodel/character_german_kriegsmarine");
	character\_utility::attachFromArray(xmodelalias\head_axis::main());
	self.voice = "german";
}

precache()
{
	precacheModel("xmodel/character_german_kriegsmarine");
	character\_utility::precacheModelArray(xmodelalias\head_axis::main());
}
