// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("xmodel/axis_default");
	character\_utility::attachFromArray(xmodelalias\head_axis::main());
	self setViewmodel("xmodel/viewmodel_hands_whermact");
	self.voice = "american";
}

precache()
{
	precacheModel("xmodel/axis_default");
	character\_utility::precacheModelArray(xmodelalias\head_axis::main());
	precacheModel("xmodel/viewmodel_hands_whermact");
}
