// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("xmodel/playerbody_british_airborne_clean");
	character\_utility::attachFromArray(xmodelalias\head_allied::main());
	self.hatModel = "xmodel/helmet_british_airborne";
	self attach(self.hatModel);
	self.voice = "american";
}

precache()
{
	precacheModel("xmodel/playerbody_british_airborne_clean");
	character\_utility::precacheModelArray(xmodelalias\head_allied::main());
	precacheModel("xmodel/helmet_british_airborne");
}
