// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("xmodel/playerbody_german_wehrmacht_clean");
	character\_utility::attachFromArray(xmodelalias\head_allied::main());
	self.hatModel = "xmodel/germanhelmet";
	self attach(self.hatModel);
	self.voice = "american";
}

precache()
{
	precacheModel("xmodel/playerbody_german_wehrmacht_clean");
	character\_utility::precacheModelArray(xmodelalias\head_allied::main());
	precacheModel("xmodel/germanhelmet");
}
