// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("xmodel/character_Pavlov");
	self attach("xmodel/head_Pavlov");
	self.hatModel = "xmodel/equipment_pavlov_ushanka";
	self attach(self.hatModel);
	self.voice = "pavlov";
}

precache()
{
	precacheModel("xmodel/character_Pavlov");
	precacheModel("xmodel/head_Pavlov");
	precacheModel("xmodel/equipment_pavlov_ushanka");
}
