// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	character\_utility::setModelFromArray(xmodelalias\body_soviet_overcoat::main());
	character\_utility::attachFromArray(xmodelalias\head_allied::main());
	self.voice = "russian";
}

precache()
{
	character\_utility::precacheModelArray(xmodelalias\body_soviet_overcoat::main());
	character\_utility::precacheModelArray(xmodelalias\head_allied::main());
}
