// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("xmodel/character_soviet_tankcrew");
	character\_utility::attachFromArray(xmodelalias\head_allied::main());
	self.hatModel = "xmodel/equipment_russian_tankhelmet";
	self attach(self.hatModel);
	self.voice = "russian";
}

precache()
{
	precacheModel("xmodel/character_soviet_tankcrew");
	character\_utility::precacheModelArray(xmodelalias\head_allied::main());
	precacheModel("xmodel/equipment_russian_tankhelmet");
}
