// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("xmodel/character_soviet_tunic");
	character\_utility::attachFromArray(xmodelalias\head_allied::main());
	self.voice = "russian";
}

precache()
{
	precacheModel("xmodel/character_soviet_tunic");
	character\_utility::precacheModelArray(xmodelalias\head_allied::main());
}
