// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("xmodel/character_german_kriegsmarine");
	self attach("xmodel/head_Waters");
	self.voice = "waters";
}

precache()
{
	precacheModel("xmodel/character_german_kriegsmarine");
	precacheModel("xmodel/head_Waters");
}
