// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{

	switch(randomint(3))
	{
	case 0:
		character\mp_german_waffen01::main();
		break;
	case 1:
		character\mp_german_waffen02::main();
		break;
	case 2:
		character\mp_german_waffen03::main();
		break;
	}
}

precache()
{
	character\mp_german_waffen01::precache();
	character\mp_german_waffen02::precache();
	character\mp_german_waffen03::precache();
}
