// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{

	switch(randomint(3))
	{
	case 0:
		character\mp_german_waffen01_winter::main();
		break;
	case 1:
		character\mp_german_waffen02_winter::main();
		break;
	case 2:
		character\mp_german_waffen03_winter::main();
		break;
	}
}

precache()
{
	character\mp_german_waffen01_winter::precache();
	character\mp_german_waffen02_winter::precache();
	character\mp_german_waffen03_winter::precache();
}
