// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{

	switch(randomint(2))
	{
	case 0:
		character\mp_russian_conscript01_winter::main();
		break;
	case 1:
		character\mp_russian_conscript02_winter::main();
		break;
	}
}

precache()
{
	character\mp_russian_conscript01_winter::precache();
	character\mp_russian_conscript02_winter::precache();
}
