// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{

	switch(randomint(2))
	{
	case 0:
		character\mp_russian_veteran01::main();
		break;
	case 1:
		character\mp_russian_veteran02::main();
		break;
	}
}

precache()
{
	character\mp_russian_veteran01::precache();
	character\mp_russian_veteran02::precache();
}
